# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RA6hXi40ApauoaYy59lPZkUOpfV_ANK_
"""

!pip install -r requirements.txt

!pip install -r requirements.txt

langchain
transformers
torch
python-dotenv

!cat requirements.txt

!pip install langchain transformers torch python-dotenv

langchain
transformers
torch
python-dotenv

!pip install langchain transformers torch python-dotenv

langchain
transformers
torch
python-dotenv

import langchain
import transformers
import torch
import dotenv  # for python-dotenv

!pip install -U transformers

from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
{"role": "user", "content": "Who are you?"},
]
pipe(messages)

!pip install --upgrade transformers

!pip install transformers==4.33.1

from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
{"role": "user", "content": "Who are you?"},
]
pipe(messages)

# Install required libraries
!pip install gradio

import gradio as gr
import ast
import traceback

# Function for normal chat explanation
def chatbot_response(user_input):

    if "list comprehension" in user_input.lower():
        return """
List Comprehension in Python:

Syntax:
[expression for item in iterable]

Example:
squares = [x**2 for x in range(10)]

Output:
[0,1,4,9,16,25,36,49,64,81]

It is used to create lists in a short and readable way.
"""

    elif "loop" in user_input.lower():
        return """
Python Loop Example:

for i in range(5):
    print(i)

Output:
0 1 2 3 4
"""

    else:
        return "I can explain Python concepts or fix Python code."

# Function to check python syntax
def fix_python_code(code):

    try:
        ast.parse(code)
        return "✅ No Syntax Error Found\n\nYour code is correct."

    except SyntaxError:
        error = traceback.format_exc()

        # simple fix example
        fixed = code.replace("print(", "print(")

        return f"❌ Syntax Error Found\n\nError:\n{error}\n\nCheck indentation or missing symbols."

# Gradio UI
with gr.Blocks() as demo:

    gr.Markdown("# 🤖 Granite Chatbot")
    gr.Markdown("Python Chat + Code Fixer")

    with gr.Tab("Chat"):
        user_text = gr.Textbox(label="Ask Python Question")
        output = gr.Textbox(label="Answer")
        btn = gr.Button("Send")
        btn.click(chatbot_response, inputs=user_text, outputs=output)

    with gr.Tab("Code Fixer"):
        code_input = gr.Textbox(lines=10,label="Paste Python Code")
        result = gr.Textbox(label="Result")
        fix_btn = gr.Button("Check Code")
        fix_btn.click(fix_python_code, inputs=code_input, outputs=result)

demo.launch()

# Install libraries
!pip install gradio fpdf

import gradio as gr
import ast
import traceback
from fpdf import FPDF

chat_history = []

# Chatbot function
def chat_response(user_input):

    if "list comprehension" in user_input.lower():
        reply = """
List Comprehension in Python

Syntax:
[expression for item in iterable]

Example:
squares = [x**2 for x in range(10)]

Output:
[0,1,4,9,16,25,36,49,64,81]
"""
    else:
        reply = "Ask Python question or paste Python code to fix."

    chat_history.append("User: " + user_input)
    chat_history.append("Bot: " + reply)

    return reply

# Python code checker
def check_code(code):

    try:
        ast.parse(code)
        result = "✅ No Syntax Error Found\n\nCode is correct."
    except:
        result = "❌ Syntax Error Found\n\n" + traceback.format_exc()

    chat_history.append("Code:\n" + code)
    chat_history.append("Result:\n" + result)

    return result

# Download TXT
def download_txt():
    text = "\n".join(chat_history)
    with open("chat.txt","w") as f:
        f.write(text)
    return "chat.txt"

# Download PDF
def download_pdf():

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    for line in chat_history:
        pdf.cell(200,10,txt=line,ln=True)

    pdf.output("chat.pdf")
    return "chat.pdf"


# UI
with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("# 🤖 Granite Chatbot")
    gr.Markdown("Python Chat + Code Fixer")

    with gr.Tab("Chat"):

        question = gr.Textbox(label="Ask Python Question")
        answer = gr.Textbox(label="Answer")

        send = gr.Button("Send")

        send.click(chat_response, inputs=question, outputs=answer)

    with gr.Tab("Code Fixer"):

        code = gr.Textbox(lines=10,label="Paste Python Code")
        result = gr.Textbox(label="Result")

        check = gr.Button("Check Code")

        check.click(check_code, inputs=code, outputs=result)

    with gr.Tab("Download"):

        txt = gr.File()
        pdf = gr.File()

        btn1 = gr.Button("Download TXT")
        btn2 = gr.Button("Download PDF")

        btn1.click(download_txt, outputs=txt)
        btn2.click(download_pdf, outputs=pdf)

demo.launch()

!pip install gradio

import gradio as gr
import ast
import traceback

def check_code(code):
    try:
        ast.parse(code)
        return "✅ No Syntax Error Found"
    except:
        return "❌ Syntax Error Found\n" + traceback.format_exc()

def explain(text):
    if "list comprehension" in text.lower():
        return "List comprehension is used to create lists in one line. Example: [x**2 for x in range(10)]"
    else:
        return "Ask Python questions."

with gr.Blocks() as demo:

    gr.Markdown("# Granite Chatbot")

    with gr.Tab("Chat"):
        q = gr.Textbox(label="Ask Question")
        a = gr.Textbox(label="Answer")
        btn = gr.Button("Send")
        btn.click(explain, inputs=q, outputs=a)

    with gr.Tab("Code Fixer"):
        code = gr.Textbox(lines=10,label="Paste Python Code")
        out = gr.Textbox(label="Result")
        btn2 = gr.Button("Check Code")
        btn2.click(check_code, inputs=code, outputs=out)

demo.launch()